import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {SSAOPass} from 'three/addons/postprocessing/SSAOPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {labels} from './labels.js';
const $=id=>document.getElementById(id), data=window.SKULL_DATA;
const views={f:{title:'頭骨前面觀',note:'完整頭顱與下頷骨',camera:[0,0,600],up:[0,1,0],cap:false,jaw:true,orientation:'前面 · 解剖左側在畫面右方'},l:{title:'頭骨左側觀',note:'可切換顱蓋；預設移除下頷骨以觀察顳骨',camera:[600,0,0],up:[0,1,0],cap:true,jaw:false,orientation:'左側 · 前方在畫面左方'},b:{title:'頭骨底面觀',note:'由下往上看 · 移除下頷骨',camera:[0,-600,0],up:[0,0,1],cap:true,jaw:false,orientation:'底面 · 上方為前，下面為後'},i:{title:'頭骨顱窩（顱底內面觀）',note:'移除顱蓋 · 由上往下觀察顱底',camera:[0,600,-5],up:[0,0,1],cap:true,jaw:false,orientation:'顱底內面 · 上方為前，下面為後'}};
let current='f',names=true,selected=null,lang='both',activeLabels=[],labelSlots=null,modelMeshes=[],width=0,height=0;
let renderer,scene,camera,controls,composer,ao;
const plane=new THREE.Plane(new THREE.Vector3(0,-1,0),27);
const palette=[0xb9cdb6,0xe1c395,0xa9c9c7,0xc1b4d3,0xc7d1a5,0xd8b19b,0xbed1de];
function decode(s,Type){let b=Uint8Array.from(atob(s),c=>c.charCodeAt(0));return new Type(b.buffer);}
function materialColor(name){let key=name.replace(/\.[lr]$/,'');let keys=[...new Set(data.meshes.map(m=>m.name.replace(/\.[lr]$/,'')))];return $('colors').checked?palette[keys.indexOf(key)%palette.length]:/^(Upper|Lower)/.test(name)?0xf2e7cd:0xd8c6a5;}
function initialize(){
 renderer=new THREE.WebGLRenderer({canvas:$('canvas'),antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.localClippingEnabled=true;renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
 scene=new THREE.Scene();scene.background=new THREE.Color(0x1b2e3b);camera=new THREE.OrthographicCamera(-200,200,160,-160,.1,2500);
 scene.add(new THREE.HemisphereLight(0xdcecf0,0x6e5540,1.5));const key=new THREE.DirectionalLight(0xffefd8,2.3);key.position.set(-150,250,320);scene.add(key);const fill=new THREE.DirectionalLight(0xb6d7eb,1.0);fill.position.set(160,30,-120);scene.add(fill);const under=new THREE.DirectionalLight(0xffe3be,1.1);under.position.set(0,-200,100);scene.add(under);
 for(const item of data.meshes){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(decode(item.positions,Float32Array),3));g.setIndex(new THREE.BufferAttribute(decode(item.indices,Uint32Array),1));g.computeVertexNormals();const m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:materialColor(item.name),roughness:.8,side:THREE.DoubleSide}));m.name=item.name;scene.add(m);modelMeshes.push(m);}
 for(const l of labels){if(l.anchor&&data.anchors[l.anchor]){l.position=[...data.anchors[l.anchor]];if(l.bone.endsWith('.l'))l.position[0]=Math.abs(l.position[0]);l.precise=true;}l.point=new THREE.Vector3(...l.position);}
 controls=new OrbitControls(camera,$('canvas'));controls.enableDamping=true;controls.dampingFactor=.1;controls.minZoom=.45;controls.maxZoom=6;controls.target.set(0,0,10);controls.addEventListener('change',drawLabels);
 composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));ao=new SSAOPass(scene,camera,1,1);ao.kernelRadius=7;ao.minDistance=.0002;ao.maxDistance=.025;composer.addPass(ao);composer.addPass(new OutputPass());
 new ResizeObserver(resize).observe($('stage'));setView('f');resize();$('loading').hidden=true;
 renderer.setAnimationLoop(()=>{controls.update();if($('xray').checked)renderer.render(scene,camera);else composer.render();drawLabels();});
 window.atlas={labels,meshes:modelMeshes,scene,camera,controls,setView,get state(){return {current,names,selected,active:activeLabels.length,cap:$('cap').checked,jaw:$('jaw').checked};}};
}
function resize(){const r=$('stage').getBoundingClientRect();width=r.width;height=r.height;$('leaders').setAttribute('viewBox',`0 0 ${width} ${height}`);renderer.setSize(width,height,false);composer?.setSize(width,height);const half=width<500?height*.49:154;camera.left=-half*width/height;camera.right=half*width/height;camera.top=half;camera.bottom=-half;camera.updateProjectionMatrix();drawLabels();}
function setView(v){labelSlots=null;current=v;selected=null;const c=views[v];$('view-title').textContent=c.title;$('view-note').textContent=c.note;$('orientation').textContent=c.orientation;$('cap').checked=c.cap;$('jaw').checked=c.jaw;camera.up.set(...c.up);camera.position.set(...c.camera);camera.zoom=1;camera.updateProjectionMatrix();controls.target.set(0,v==='f'?0:-18,10);controls.update();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('search').value='';updateModel();renderList();labelSlots=null;rebuildLabels();showDetail();}
function updateModel(){renderer.clippingPlanes=$('cap').checked?[plane]:[];for(const m of modelMeshes){const lower=m.name==='Mandible'||m.name.startsWith('Lower ');m.visible=!lower||$('jaw').checked;m.material.transparent=$('xray').checked;m.material.opacity=$('xray').checked?.35:1;m.material.depthWrite=!$('xray').checked;m.material.color.setHex(materialColor(m.name));m.material.emissive.setHex(selected&&labels.find(l=>l.id===selected)?.bone===m.name?0x315f46:0x000000);m.material.emissiveIntensity=.65;}}
function labelHTML(l){if(!names)return `<b>${String(l.number).padStart(2,'0')}</b>`;return `<b>${String(l.number).padStart(2,'0')}</b><div>${lang!=='en'?`<div class="zh">${l.zh}</div>`:''}${lang!=='zh'?`<div class="en">${l.en}</div>`:''}</div>`;}
function relevant(){let q=$('search').value.trim().toLowerCase();return q?labels.filter(l=>(l.zh+' '+l.en).toLowerCase().includes(q)):labels.filter(l=>l.views.includes(current));}
function renderList(){const ls=relevant();$('list-title').textContent=$('search').value?'全部視角的搜尋結果':'此視角的構造';$('count').textContent=`${ls.length} 項`;$('structure-list').replaceChildren();for(const l of ls){const b=document.createElement('button');b.className='structure'+(l.id===selected?' selected':'');b.dataset.id=l.id;b.innerHTML=`<span class="num">${String(l.number).padStart(2,'0')}</span><div><strong>${names?l.zh:'構造 '+String(l.number).padStart(2,'0')}</strong><small>${names?l.en:'名稱已隱藏'}</small></div><span class="hint">↗</span>`;b.onclick=()=>choose(l);$('structure-list').append(b);}if(!ls.length)$('structure-list').innerHTML='<p class="empty">沒有符合的構造。</p>';}
function choose(l){if(!l.views.includes(current)){const q=$('search').value;setView(l.views[0]);$('search').value=q;}selected=l.id;if(l.position[1]>27)$('cap').checked=false;if(l.bone==='Mandible')$('jaw').checked=true;updateModel();renderList();rebuildLabels();showDetail(l);}
function showDetail(l){const div=$('detail');div.querySelector('.detail-number').textContent=l?String(l.number).padStart(2,'0'):'◎';div.querySelector('h3').innerHTML=l?(names?`${l.zh}<small>${l.en}</small>`:`構造 ${String(l.number).padStart(2,'0')} · 名稱已隱藏`):(names?'從任一標示開始探索':'名稱已全部隱藏');div.querySelector('p').textContent=l?(names?`${l.note} ${l.precise?'定位：原模型指線端點。':'定位：位置導引，請以原圖核對細節。'}`:'可旋轉觀察與點選編號；按「顯示所有名稱」揭曉。'):(names?'點選名稱可突出所在骨骼。虛線標記為位置導引；實際小孔形態請搭配原圖辨識。':'模型標示、側欄與詳細說明均已遮蔽答案，保留編號供自測。');}
function focusLeader(id){$('leaders').classList.toggle('has-focus',!!id);for(const o of activeLabels){const focus=o.l.id===id;o.group.classList.toggle('focused',focus);o.button.classList.toggle('traced',focus);o.dot.setAttribute('r',focus?5:3.6);if(focus)$('leaders').append(o.group);}}
function rebuildLabels(){const ls=labels.filter(l=>l.views.includes(current));$('labels').replaceChildren();$('leaders').replaceChildren();const svg=name=>document.createElementNS('http://www.w3.org/2000/svg',name);activeLabels=ls.map(l=>{const button=document.createElement('button');button.className='label '+(l.precise?'':'guide')+(l.id===selected?' selected':'');button.dataset.id=l.id;button.innerHTML=labelHTML(l);button.setAttribute('aria-label',names?l.zh:`構造 ${l.number}`);button.onclick=()=>choose(l);button.onpointerenter=button.onfocus=()=>focusLeader(l.id);button.onpointerleave=button.onblur=()=>focusLeader(selected);$('labels').append(button);const group=svg('g'),halo=svg('line'),line=svg('line'),dot=svg('circle');group.dataset.id=l.id;halo.classList.add('leader-halo');line.classList.add('leader-main');if(!l.precise)line.classList.add('guide');dot.setAttribute('r',3.6);group.append(halo,line,dot);$('leaders').append(group);return {l,button,group,halo,line,dot};});focusLeader(selected);drawLabels();}
const projection=new THREE.Vector3();
function drawLabels(){if(!camera||!width||!height)return;camera.updateMatrixWorld();const items=activeLabels.map(o=>{projection.copy(o.l.point).project(camera);return {...o,x:(projection.x+1)*width/2,y:(1-projection.y)*height/2,visible:projection.z>-1&&projection.z<1};});if(!labelSlots){const sorted=[...items].sort((a,b)=>a.x-b.x),mid=Math.ceil(sorted.length/2);labelSlots=[sorted.slice(0,mid),sorted.slice(mid)].map(group=>group.sort((a,b)=>a.y-b.y).map(o=>o.l.id));}const byId=new Map(items.map(o=>[o.l.id,o]));for(let side=0;side<2;side++){const group=labelSlots[side].map(id=>byId.get(id)).filter(Boolean);const step=Math.min(width<500?46:43,(height-44)/Math.max(1,group.length));const start=Math.max(12,(height-step*group.length)/2);group.forEach((o,i)=>{let clipped=$('cap').checked&&o.l.position[1]>27;let hiddenJaw=!$('jaw').checked&&o.l.bone==='Mandible';let offscreen=o.x<0||o.x>width||o.y<0||o.y>height;let visible=o.visible&&!hiddenJaw&&!clipped&&!offscreen;o.button.style.display=visible?'flex':'none';o.group.style.display=visible?'':'none';if(!visible)return;const bw=o.button.offsetWidth,bh=o.button.offsetHeight;const x=side?width-bw-4:4,y=start+i*step;o.button.style.transform=`translate(${x}px,${y}px)`;for(const line of [o.halo,o.line]){line.setAttribute('x1',side?x:x+bw);line.setAttribute('y1',y+bh/2);line.setAttribute('x2',o.x);line.setAttribute('y2',o.y);}o.dot.setAttribute('cx',o.x);o.dot.setAttribute('cy',o.y);});}}
function toggleNames(value){names=value;document.body.classList.toggle('hidden-names',!value);if(!value)$('reference-dialog').close();$('hide').setAttribute('aria-pressed',!value);$('show').setAttribute('aria-pressed',value);renderList();rebuildLabels();showDetail(labels.find(l=>l.id===selected));}
$('hide').onclick=()=>toggleNames(false);$('show').onclick=()=>toggleNames(true);$('views').onclick=e=>{const b=e.target.closest('[data-view]');if(b)setView(b.dataset.view);};$('reset').onclick=()=>setView(current);$('search').oninput=renderList;for(const id of ['cap','jaw','colors','xray'])$(id).onchange=()=>{updateModel();drawLabels();};$('language').onchange=()=>{lang=$('language').value;rebuildLabels();};$('clear').onclick=()=>{selected=null;updateModel();renderList();rebuildLabels();showDetail();};$('source-button').onclick=()=>$('source-dialog').showModal();$('reference').onclick=()=>{if(!names){$('detail').querySelector('p').textContent='原圖包含答案。請先按「顯示所有名稱」再開啟原圖。';return;}$('reference-img').src=window.REFERENCE_IMAGES?.[current]||`assets/reference-${current}.png`;$('reference-dialog').showModal();};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
try{initialize();}catch(e){$('loading').textContent='無法啟動 3D：'+e.message+'。請使用支援 WebGL 的 Chrome 或 Edge。';console.error(e);}
