// Four supplied plates transcribed in full. f=front, l=left, b=base, i=internal.
// Coordinates in millimetres in the extracted atlas frame; +X = subject's left.
export const labels = [
['frontal','額骨','Frontal bone','f',[0,64,91],'Frontal bone','Squamous part of frontal bone','形成前額與眼眶上壁。'],
['temporal','顳骨','Temporal bone','f',[67,4,14],'Temporal bone.l',null,'位於頭顱兩側；其岩部參與顱底。'],
['sphenoid','蝶骨','Sphenoid','f',[34,-1,53],'Sphenoid bone',null,'位於顱底中央，並參與眼眶後壁。'],
['ethmoid','篩骨','Ethmoid','fl',[13,-6,70],'Ethmoid bone',null,'參與眼眶內側壁、鼻腔頂與骨性鼻中隔。'],
['lacrimal','淚骨','Lacrimal bone','fl',[18,-9,80],'Lacrimal bone.l',null,'位於眼眶內側壁前部。'],
['zygomatic','顴骨','Zygomatic bone','f',[53,-35,71],'Zygomatic bone.l',null,'形成面頰突起及眼眶外下側緣。'],
['septum','鼻中隔','Nasal septum','f',[0,-32,83],'Vomer',null,'圖中標示骨性部分：上方篩骨垂直板，下方犁骨；完整鼻中隔還包括軟骨。'],
['perpendicular','篩骨垂直板','Perpendicular plate of ethmoid','f',[0,-18,78],'Ethmoid bone',null,'篩骨向下延伸的正中薄板，構成骨性鼻中隔上部。'],
['vomer','犁骨','Vomer','f',[0,-45,70],'Vomer',null,'構成骨性鼻中隔的後下部。'],
['supraorbital','眶上孔','Supraorbital foramen','f',[25,16,91],'Frontal bone','(Supra-orbital notch)','位於眶上緣；本模型呈現眶上切跡型態，不一定是完整封閉孔。'],
['nasal','鼻骨','Nasal bone','f',[5,-4,102],'Nasal bone.l',null,'左右成對，形成鼻樑。'],
['superior-fissure','眶上裂','Superior orbital fissure','fi',[29,-2,39],'Sphenoid bone',null,'蝶骨大翼與小翼之間的裂隙。'],
['inferior-fissure','眶下裂','Inferior orbital fissure','f',[35,-26,60],'Maxilla.l',null,'位於眼眶底與外側壁交界。'],
['infraorbital','眶下孔','Infraorbital foramen','fl',[30,-36,88],'Maxilla.l',null,'位於上頷骨前面、眶下緣下方。'],
['maxilla','上頷骨','Maxilla','fl',[23,-50,85],'Maxilla.l',null,'形成上顎，支持上排牙齒並參與硬腭。'],
['middle-concha','中鼻甲','Middle nasal concha','f',[8,-24,73],'Ethmoid bone',null,'為篩骨的一部分，向鼻腔內突出。'],
['inferior-concha','下鼻甲','Inferior nasal concha','f',[12,-39,82],'Inferior nasal concha bone.l',null,'獨立成對的小骨，位於鼻腔外側壁。'],
['mandible','下頷骨','Mandible','f',[23,-94,69],'Mandible',null,'下顎骨，支持下排牙齒。'],
['mental','頦孔','Mental foramen','f',[27,-81,79],'Mandible','Mental foramen','位於下頷骨體外側面。'],
['mandibular-fossa','下頷窩','Mandibular fossa','l',[52,-33,8],'Temporal bone.l',null,'顳骨上與下頷骨頭相對的關節凹窩。'],
['external-meatus','外耳道','External auditory meatus','l',[67,-29,-6],'Temporal bone.l',null,'位於顳骨外側的外耳道骨性開口。'],
['occipital','枕骨','Occipital bone','l',[45,2,-78],'Occipital bone',null,'構成顱骨後下部，中央有枕骨大孔。'],
['mastoid','乳突','Mastoid process','lb',[53,-50,-22],'Temporal bone.l','Mastoid process','顳骨向下突出的粗大骨突，位於外耳道後下方。'],
['temporal-zygomatic','顳骨顴突','Zygomatic process of temporal bone','lb',[64,-20,30],'Temporal bone.l',null,'顳骨向前伸出的骨突，構成顴弓後部。'],
['zygomatic-temporal','顴骨顳突','Temporal process of zygomatic bone','lb',[62,-23,48],'Zygomatic bone.l',null,'顴骨向後延伸的骨突，構成顴弓前部。'],
['arch','顴弓','Zygomatic arch','lb',[64,-21,38],'Zygomatic bone.l',null,'由顳骨顴突與顴骨顳突相接形成。'],
['squamous','鱗狀縫','Squamous suture','l',[65,22,-5],'Temporal bone.l',null,'顳骨鱗部與頂骨之間的骨縫；截去顱蓋時部分骨縫也會消失。'],
['greater-wing','蝶骨大翼','Sphenoid, greater wing','l',[50,9,45],'Sphenoid bone','Greater wing','蝶骨向兩側伸展的大翼。'],
['styloid','莖突','Styloid process','lb',[38,-53,1],'Temporal bone.l','Styloid process of temporal bone','顳骨向下延伸的細長骨突。'],
['incisive','門齒孔','Incisive foramen','b',[0,-62,86],'Maxilla.l',null,'位於硬腭前部，上中門齒後方。'],
['ovale','卵圓孔','Foramen ovale','bi',[24,-22,12],'Sphenoid bone','Foramen ovale','位於蝶骨大翼。'],
['spinosum','棘孔','Foramen spinosum','bi',[31,-25,7],'Sphenoid bone','Foramen spinosum','位於卵圓孔後外側的小孔。'],
['carotid','頸動脈管','Carotid canal','b',[28,-38,-7],'Temporal bone.l',null,'此處標示顱底外面的管口位置。'],
['jugular','頸靜脈孔','Jugular foramen','bi',[27,-39,-22],'Temporal bone.l',null,'位於顳骨與枕骨之間。'],
['hypoglossal','舌下神經管','Hypoglossal canal','bi',[15,-41,-28],'Occipital bone','Hypoglossal canal','位於枕骨大孔前外側、枕髁上方。'],
['palatine-process','上頷骨腭突','Palatine process of maxilla','b',[12,-61,66],'Maxilla.l',null,'形成硬腭前部。'],
['horizontal-plate','腭骨水平板','Horizontal plate of palatine bone','b',[12,-57,40],'Palatine bone.l',null,'形成硬腭後部。'],
['hard-palate','硬腭','Hard palate','b',[0,-60,57],'Maxilla.l',null,'由上頷骨腭突及腭骨水平板共同形成。'],
['lacerum','破裂孔','Foramen lacerum','bi',[16,-30,6],'Sphenoid bone',null,'位於蝶骨、顳骨與枕骨交界；活體中主要由軟骨填充。'],
['stylomastoid','莖乳孔','Stylomastoid foramen','b',[43,-42,-14],'Temporal bone.l',null,'位於莖突與乳突之間。'],
['condyle','枕髁','Occipital condyle','b',[16,-48,-32],'Occipital bone','Occipital condyle','位於枕骨大孔左右兩側的關節隆起。'],
['magnum','枕骨大孔','Foramen magnum','bi',[0,-43,-40],'Occipital bone','Foramen magnum','枕骨的大型開口，連接顱腔與椎管。'],
['rotundum','圓孔','Foramen rotundum','i',[20,-7,27],'Sphenoid bone','Foramen rotundum','位於蝶骨大翼，較卵圓孔靠前。'],
['internal-meatus','內耳道','Internal auditory meatus','i',[29,-8,-19],'Temporal bone.l',null,'顳骨岩部後面的內耳道開口。'],
['crista','雞冠','Crista galli','i',[0,5,61],'Ethmoid bone',null,'篩骨向顱腔內突出的正中骨嵴。'],
['cribriform','篩板','Cribriform plate','i',[6,-2,61],'Ethmoid bone',null,'雞冠兩側的篩骨水平板。'],
['olfactory','嗅孔','Olfactory foramina','i',[6,4,67],'Ethmoid bone',null,'篩板上的細小孔群；此模型無法逐孔辨識，標記為篩板區域導引。'],
['optic','視神經管（孔）','Optic canal (foramen)','i',[13,4,39],'Sphenoid bone','Optic canal','位於蝶骨小翼根部。'],
['sella','蝶鞍（腦下腺窩）','Sella turcica (hypophyseal fossa)','i',[0,-5,23],'Sphenoid bone','Hypophysial fossa','腦下腺窩位於蝶鞍中央；蝶鞍是更廣的鞍形骨性結構。']
].map((r,index)=>({id:r[0],zh:r[1],en:r[2],views:r[3].split(''),position:r[4],bone:r[5],anchor:r[6],note:r[7],number:index+1}));
