// Offline browser verification of the standalone page. Writes assets/verification.json.
const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const {pathToFileURL}=require('node:url');const path=require('node:path');
(async()=>{const exe=fs.existsSync('/opt/pw-browsers/chromium')?{executablePath:'/opt/pw-browsers/chromium',args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}:{channel:'chrome'};
const browser=await chromium.launch({headless:true,...exe});const context=await browser.newContext({viewport:{width:1440,height:1100},offline:true});const page=await context.newPage();const errors=[],http=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))http.push(r.url())});
await page.goto(pathToFileURL(path.resolve('神經與顱骨3D.html')).href);await page.waitForFunction(()=>window.atlas,null,{timeout:120000});
const report={date:new Date().toISOString(),browser:await browser.version(),offline:true,checks:[]};const pass=x=>{report.checks.push(x);console.log('✓',x);};
const info=await page.evaluate(()=>({n:atlas.labels.length,unmatched:atlas.labels.filter(l=>!l.matches.length).map(l=>l.id),meshes:atlas.meshes.length,groups:Object.fromEntries(Object.keys(atlas.groups).map(g=>[g,atlas.labels.filter(l=>l.groups.includes(g)).length]))}));
const ring=await page.evaluate(()=>atlas.annulus['.l']);for(const n of ['Trochlear nerve (IV)','Ophthalmic nerve','Superior ophthalmic vein'])assert.equal(ring[n].where,'outside',n);for(const n of ['Oculomotor nerve (III)','Abducens nerve (VI)','Optic nerve (II)','Ophthalmic artery'])assert.equal(ring[n].where,'inside',n);
assert.deepEqual(info.unmatched,[]);pass(`${info.n} entries, every one matched to a source mesh or guide (${info.meshes} meshes incl. schematics)`);
// Every foramen that a nerve passes through must exist.
assert.equal(await page.evaluate(()=>atlas.labels.flatMap(l=>l.via).filter(id=>!atlas.labels.some(l=>l.id===id)).length),0);pass('All nerve → foramen links resolve');
// Nerves reach their foramina in the source geometry (mm).
const gaps=await page.evaluate(()=>{const pairs=[['Maxillary nerve.l','rotundum'],['Optic nerve (II).l','optic-canal'],['Trigeminal nerve (V).l','ovale'],['Hypoglossal nerve (XII).l','hypoglossal-canal'],['Middle meningeal artery.l','spinosum'],['Abducens nerve (VI).l','sof'],['Vagus nerve (X).l','jugular'],['Facial nerve (VII).l','iam']];return Object.fromEntries(pairs.map(([m,id])=>{const mesh=atlas.meshes.find(x=>x.name===m),p=atlas.labels.find(l=>l.id===id).point,a=mesh.geometry.attributes.position;let d=Infinity;for(let i=0;i<a.count;i++){const dx=a.getX(i)-p.x,dy=a.getY(i)-p.y,dz=a.getZ(i)-p.z;d=Math.min(d,Math.hypot(dx,dy,dz));}return [m+' → '+id,+d.toFixed(1)];}));});
for(const [k,d] of Object.entries(gaps))assert.ok(d<5,k+' '+d);pass('Nerve-to-foramen distances (mm): '+JSON.stringify(gaps));
async function layout(){for(let i=0;i<3;i++)await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.waitForTimeout(150);return page.evaluate(()=>{const stage=document.querySelector('#stage').getBoundingClientRect(),rs=[...document.querySelectorAll('.label')].map(e=>e.getBoundingClientRect()),pairs=[];for(let i=0;i<rs.length;i++)for(let j=i+1;j<rs.length;j++)if(Math.min(rs[i].right,rs[j].right)-Math.max(rs[i].left,rs[j].left)>1&&Math.min(rs[i].bottom,rs[j].bottom)-Math.max(rs[i].top,rs[j].top)>1)pairs.push([i,j]);return{overlaps:pairs.length,outside:rs.filter(r=>r.left<stage.left-1||r.right>stage.right+1||r.top<stage.top-1||r.bottom>stage.bottom+1).length,overflow:document.documentElement.scrollWidth>innerWidth};});}
for(const [g,count] of Object.entries(info.groups)){await page.click(`[data-view="${g}"]`);assert.equal(await page.locator('.label').count(),count);assert.deepEqual(await layout(),{overlaps:0,outside:0,overflow:false},g);
 const onscreen=await page.evaluate(()=>document.querySelectorAll('.label.offscreen').length);assert.equal(onscreen,0,g+' offscreen anchors');
 await page.locator('.structure').first().click();await page.click('#hide');assert.equal(await page.locator('.label .zh,.label .en').count(),0);assert.ok((await page.locator('#structure-list').innerText()).includes('名稱已隱藏'));assert.ok((await page.locator('#detail h3').innerText()).includes('名稱已隱藏'));assert.equal(await page.locator('#detail-meta button').filter({hasText:'→'}).count(),0);
 await page.click('#notes-button');assert.equal(await page.locator('#notes-dialog').evaluate(e=>e.open),false);await page.click('#show');assert.equal(await page.locator('.label .zh').count(),count);}
pass('Themes '+JSON.stringify(info.groups)+': labels in bounds, no overlaps, anchors on screen, hide/show guards answers');
await page.locator('#search').fill('小考 9');assert.equal(await page.locator('.structure').count(),1);await page.locator('.structure').click();assert.equal(await page.evaluate(()=>atlas.state.selected),'maxillary-sinus');await page.locator('#search').fill('');pass('Quiz-number search');
await page.click('[data-view="n"]');await page.locator('.structure',{hasText:'V2 上頷神經'}).click();await page.locator('#detail-meta button',{hasText:'圓孔'}).click();assert.equal(await page.evaluate(()=>atlas.state.current+':'+atlas.state.selected),'f:rotundum');assert.ok(await page.locator('#detail-meta button',{hasText:'V2'}).count()>=1);pass('Nerve → foramen jump (V2 → 圓孔) and foramen lists the nerves');
const iso=await page.evaluate(()=>{atlas.setGroup('n');atlas.select('cn3');const vis=atlas.meshes.filter(m=>m.userData.category==='nerve'&&m.visible).map(m=>m.name);const lines=[...document.querySelectorAll('#leaders g')].filter(g=>g.style.display!=='none').map(g=>g.dataset.id);return {vis,lines};});
await page.waitForTimeout(300);const lines=await page.evaluate(()=>[...document.querySelectorAll('#leaders g')].filter(g=>g.style.display!=='none').map(g=>g.dataset.id));
const dim=await page.evaluate(()=>atlas.meshes.filter(m=>m.userData.category==='nerve'&&m.visible).map(m=>[m.name,m.material.opacity]));assert.ok(dim.filter(([n])=>n.startsWith('Oculomotor')).every(([,o])=>o===1));assert.ok(dim.filter(([n])=>n.startsWith('Facial')).every(([,o])=>o===.15)&&dim.some(([n])=>n.startsWith('Facial')));
await page.locator('#nerve-dim').fill('0');const hidden=await page.evaluate(()=>atlas.meshes.filter(m=>m.userData.category==='nerve'&&m.visible).map(m=>m.name));assert.deepEqual([...new Set(hidden.map(n=>n.replace(/\.[lr]$/,'')))],['Oculomotor nerve (III)']);await page.locator('#nerve-dim').fill('0.15');assert.deepEqual(lines,['cn3']);
await page.evaluate(()=>atlas.select('cn5'));await page.waitForTimeout(300);const v=await page.evaluate(()=>atlas.meshes.filter(m=>m.userData.category==='nerve'&&m.visible&&m.material.opacity===1).map(m=>m.name));assert.ok(v.some(n=>n.startsWith('Maxillary nerve'))&&!v.some(n=>n.startsWith('Facial')));
await page.click('#clear');await page.waitForTimeout(300);assert.ok(await page.evaluate(()=>atlas.meshes.filter(m=>m.userData.category==='nerve'&&m.visible).length>20));assert.equal(await page.evaluate(()=>[...document.querySelectorAll('#leaders g')].filter(g=>g.style.display==='none').length),0);
pass('Selecting a cranial nerve emphasises it (both sides; V includes V1–V3), other nerves fade to the adjustable opacity (0 hides them), other leader lines hidden until cleared');
await page.evaluate(()=>{atlas.setGroup('n');atlas.select('v2');});await page.locator('#detail-meta button',{hasText:'圓孔'}).click();
await page.locator('#detail-meta button',{hasText:'放大'}).click();assert.ok(await page.evaluate(()=>atlas.camera.zoom>=4.5));pass('Zoom-to-structure button');
assert.equal(await page.evaluate(()=>atlas.annulus['.l']['Trochlear nerve (IV)'].where),'outside');await page.click('[data-view="o"]');await page.click('#apex-view');assert.equal(await page.evaluate(()=>atlas.state.selected),'annulus');assert.ok(await page.evaluate(()=>atlas.meshes.find(m=>m.name==='Trochlear nerve (IV).l').material.clippingPlanes?.length===1));pass('Tendinous ring: IV, frontal nerve and SOV outside; III, VI, II, ophthalmic artery inside; apex view');
await page.click('[data-view="f"]');assert.ok(await page.evaluate(()=>atlas.meshes.find(m=>m.name==='Frontal bone').material.clippingPlanes?.length===1));await page.locator('#section-panel summary').click();await page.locator('#cut-y').uncheck();assert.ok(await page.evaluate(()=>!atlas.meshes.find(m=>m.name==='Frontal bone').material.clippingPlanes));pass('Horizontal skull cut toggles');
await page.locator('#cut-x').check();assert.equal(await page.evaluate(()=>{const m=atlas.meshes.find(m=>m.userData.category==='cortex');return m.material.clippingPlanes?.[0].normal.x;}),1);
await page.locator('#cut-x-flip').click();assert.equal(await page.evaluate(()=>atlas.meshes.find(m=>m.userData.category==='cortex').material.clippingPlanes[0].normal.x),-1);
await page.locator('#cut-z').check();assert.equal(await page.evaluate(()=>atlas.meshes.find(m=>m.userData.category==='nerve').material.clippingPlanes.length),2);
await page.locator('#cut-x-nerve').uncheck();await page.locator('#cut-z-brain').uncheck();assert.equal(await page.evaluate(()=>[atlas.meshes.find(m=>m.userData.category==='nerve').material.clippingPlanes.length,atlas.meshes.find(m=>m.userData.category==='cortex').material.clippingPlanes.length,atlas.meshes.find(m=>m.name==='Frontal bone').material.clippingPlanes.length].join()),'1,1,2');
for(const k of ['bone','brain','nerve','other'])await page.locator('#cut-z-'+k).uncheck();assert.equal(await page.evaluate(()=>atlas.meshes.find(m=>m.name==='Frontal bone').material.clippingPlanes.length),1);
await page.locator('#cut-x').uncheck();await page.locator('#cut-z').uncheck();pass('Sagittal and coronal sections, flip side, and per-plane bone / brain / nerve / other scope');
assert.ok(await page.evaluate(()=>{atlas.setGroup('q');return atlas.meshes.find(m=>m.name==='guide:on-sheath.l').visible&&atlas.labels.find(l=>l.id==='dura').anchorMesh.name==='guide:on-sheath.l';}));pass('Optic nerve dural sheath shown and quiz 2 anchored on it');
const oc=await page.evaluate(()=>{atlas.setGroup('e');const n=p=>atlas.meshes.filter(m=>m.name.startsWith(p)&&m.name.endsWith('.l')).length;return {aca:n('guide:aca-'),vortex:n('guide:vortex-'),lpca:n('guide:lpca-in-'),cra:n('Central retinal artery'),spca:n('Short posterior ciliary'),mac:n('guide:mac'),zinn:n('guide:zinn')};});
assert.deepEqual(oc,{aca:7,vortex:4,lpca:2,cra:1,spca:1,mac:1,zinn:1});
const vf=await page.evaluate(()=>{atlas.select('cra');const o=n=>atlas.meshes.find(m=>m.name===n).material.opacity;return [o('Central retinal artery.l'),o('Lacrimal artery.l')];});assert.equal(vf[0],1);assert.ok(vf[1]<=.15);
pass('Ocular vessel theme: CRA, SPCA, LPCA (+ intraocular course), 7 anterior ciliary arteries, iris arterial circles, Zinn–Haller, 4 vortex veins; selecting a vessel fades the others');
await page.click('[data-view="c"]');assert.ok(await page.evaluate(()=>atlas.meshes.find(m=>m.name==='Cavernous sinus.l').material.clippingPlanes?.[0].normal.z===-1));pass('Cavernous theme uses coronal section on all meshes');
await page.locator('#guides').uncheck();assert.equal(await page.evaluate(()=>atlas.meshes.filter(m=>m.userData.schematic&&m.visible).length),0);await page.locator('#guides').check();await page.locator('#right').uncheck();assert.equal(await page.evaluate(()=>atlas.meshes.filter(m=>/\.r\d*$/.test(m.name)&&m.visible).length),0);await page.locator('#right').check();pass('Schematic and right-side toggles');
await page.click('#notes-button');assert.ok(await page.locator('#notes-dialog').evaluate(e=>e.open));await page.locator('#notes-content [data-go="sof"]').click();assert.equal(await page.evaluate(()=>atlas.state.selected),'sof');pass('Notes dialog jump buttons');
const box=await page.locator('#canvas').boundingBox();const before=await page.evaluate(()=>atlas.camera.position.toArray());await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+120,box.y+box.height/2+40,{steps:6});await page.mouse.up();const t0=Date.now();let prev=null,after=await page.evaluate(()=>atlas.camera.position.toArray());while(Date.now()-t0<15000){await page.waitForTimeout(400);prev=after;after=await page.evaluate(()=>atlas.camera.position.toArray());if(after.every((v,i)=>Math.abs(v-prev[i])<.01))break;}assert.notDeepEqual(before,after);assert.ok(after.every((v,i)=>Math.abs(v-prev[i])<.01),'camera did not settle');assert.ok(await page.evaluate(()=>atlas.controls.enableDamping===true));pass('Drag rotates with skull-atlas damping, then settles');
await page.setViewportSize({width:390,height:844});for(const g of Object.keys(info.groups)){await page.click(`[data-view="${g}"]`);const l=await layout();assert.equal(l.overflow,false,g);assert.equal(l.overlaps,0,g);}pass('390px mobile: no horizontal overflow or label overlap');
await page.screenshot({path:'assets/check-mobile.png'});
assert.deepEqual(errors,[]);assert.deepEqual(http,[]);pass('No page errors and no network requests (fully offline)');
report.errors=errors;report.http=http;fs.writeFileSync('assets/verification.json',JSON.stringify(report,null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1);});
