// Offline browser verification of the standalone page. Writes assets/verification.json.
const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const {pathToFileURL}=require('node:url');const path=require('node:path');
(async()=>{const exe=fs.existsSync('/opt/pw-browsers/chromium')?{executablePath:'/opt/pw-browsers/chromium',args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}:{channel:'chrome'};
const browser=await chromium.launch({headless:true,...exe});const context=await browser.newContext({viewport:{width:1440,height:1100},offline:true});const page=await context.newPage();const errors=[],http=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))http.push(r.url())});
await page.goto(pathToFileURL(path.resolve('神經與顱骨3D.html')).href);await page.waitForFunction(()=>window.atlas,null,{timeout:120000});
const report={date:new Date().toISOString(),browser:await browser.version(),offline:true,checks:[]};const pass=x=>{report.checks.push(x);console.log('✓',x);};
const info=await page.evaluate(()=>({n:atlas.labels.length,unmatched:atlas.labels.filter(l=>!l.matches.length).map(l=>l.id),meshes:atlas.meshes.length,groups:Object.fromEntries(Object.keys(atlas.groups).map(g=>[g,atlas.labels.filter(l=>l.groups.includes(g)).length]))}));
assert.deepEqual(info.unmatched,[]);pass(`${info.n} entries, every one matched to a source mesh or guide (${info.meshes} meshes incl. schematics)`);
// Every foramen that a nerve passes through must exist.
assert.equal(await page.evaluate(()=>atlas.labels.flatMap(l=>l.via).filter(id=>!atlas.labels.some(l=>l.id===id)).length),0);pass('All nerve → foramen links resolve');
// Nerves reach their foramina in the source geometry (mm).
const gaps=await page.evaluate(()=>{const pairs=[['Maxillary nerve.l','rotundum'],['Optic nerve (II).l','optic-canal'],['Trigeminal nerve (V).l','ovale'],['Hypoglossal nerve (XII).l','hypoglossal-canal'],['Middle meningeal artery.l','spinosum'],['Abducens nerve (VI).l','sof'],['Vagus nerve (X).l','jugular'],['Facial nerve (VII).l','iam']];return Object.fromEntries(pairs.map(([m,id])=>{const mesh=atlas.meshes.find(x=>x.name===m),p=atlas.labels.find(l=>l.id===id).point,a=mesh.geometry.attributes.position;let d=Infinity;for(let i=0;i<a.count;i++){const dx=a.getX(i)-p.x,dy=a.getY(i)-p.y,dz=a.getZ(i)-p.z;d=Math.min(d,Math.hypot(dx,dy,dz));}return [m+' → '+id,+d.toFixed(1)];}));});
for(const [k,d] of Object.entries(gaps))assert.ok(d<5,k+' '+d);pass('Nerve-to-foramen distances (mm): '+JSON.stringify(gaps));
async function layout(){for(let i=0;i<3;i++)await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.waitForTimeout(150);return page.evaluate(()=>{const stage=document.querySelector('#stage').getBoundingClientRect(),rs=[...document.querySelectorAll('.label')].map(e=>e.getBoundingClientRect()),pairs=[];for(let i=0;i<rs.length;i++)for(let j=i+1;j<rs.length;j++)if(Math.min(rs[i].right,rs[j].right)-Math.max(rs[i].left,rs[j].left)>1&&Math.min(rs[i].bottom,rs[j].bottom)-Math.max(rs[i].top,rs[j].top)>1)pairs.push([i,j]);return{overlaps:pairs.length,outside:rs.filter(r=>r.left<stage.left-1||r.right>stage.right+1||r.top<stage.top-1||r.bottom>stage.bottom+1).length,overflow:document.documentElement.scrollWidth>innerWidth};});}
for(const [g,count] of Object.entries(info.groups)){await page.click(`[data-view="${g}"]`);assert.equal(await page.locator('.label').count(),count);assert.deepEqual(await layout(),{overlaps:0,outside:0,overflow:false},g);
 const onscreen=await page.evaluate(()=>document.querySelectorAll('.label.offscreen').length);assert.equal(onscreen,0,g+' offscreen anchors');
 await page.locator('.structure').first().click();await page.click('#hide');assert.equal(await page.locator('.label .zh,.label .en').count(),0);assert.ok((await page.locator('#structure-list').innerText()).includes('名稱已隱藏'));assert.ok((await page.locator('#detail h3').innerText()).includes('名稱已隱藏'));assert.equal(await page.locator('#detail-meta button').filter({hasText:'→'}).count(),0);
 await page.click('#notes-button');assert.equal(await page.locator('#notes-dialog').evaluate(e=>e.open),false);await page.click('#show');assert.equal(await page.locator('.label .zh').count(),count);}
pass('Themes '+JSON.stringify(info.groups)+': labels in bounds, no overlaps, anchors on screen, hide/show guards answers');
await page.locator('#search').fill('小考 9');assert.equal(await page.locator('.structure').count(),1);await page.locator('.structure').click();assert.equal(await page.evaluate(()=>atlas.state.selected),'maxillary-sinus');await page.locator('#search').fill('');pass('Quiz-number search');
await page.click('[data-view="n"]');await page.locator('.structure',{hasText:'V2 上頷神經'}).click();await page.locator('#detail-meta button',{hasText:'圓孔'}).click();assert.equal(await page.evaluate(()=>atlas.state.current+':'+atlas.state.selected),'f:rotundum');assert.ok(await page.locator('#detail-meta button',{hasText:'V2'}).count()>=1);pass('Nerve → foramen jump (V2 → 圓孔) and foramen lists the nerves');
const iso=await page.evaluate(()=>{atlas.setGroup('n');atlas.select('cn3');const vis=atlas.meshes.filter(m=>m.userData.category==='nerve'&&m.visible).map(m=>m.name);const lines=[...document.querySelectorAll('#leaders g')].filter(g=>g.style.display!=='none').map(g=>g.dataset.id);return {vis,lines};});
await page.waitForTimeout(300);const lines=await page.evaluate(()=>[...document.querySelectorAll('#leaders g')].filter(g=>g.style.display!=='none').map(g=>g.dataset.id));
assert.deepEqual([...new Set(iso.vis.map(n=>n.replace(/\.[lr]$/,'')))],['Oculomotor nerve (III)']);assert.deepEqual(lines,['cn3']);
await page.evaluate(()=>atlas.select('cn5'));await page.waitForTimeout(300);const v=await page.evaluate(()=>atlas.meshes.filter(m=>m.userData.category==='nerve'&&m.visible).map(m=>m.name));assert.ok(v.some(n=>n.startsWith('Maxillary nerve'))&&!v.some(n=>n.startsWith('Facial')));
await page.click('#clear');await page.waitForTimeout(300);assert.ok(await page.evaluate(()=>atlas.meshes.filter(m=>m.userData.category==='nerve'&&m.visible).length>20));assert.equal(await page.evaluate(()=>[...document.querySelectorAll('#leaders g')].filter(g=>g.style.display==='none').length),0);
pass('Selecting a cranial nerve hides the other nerves (both sides kept; V includes V1–V3) and hides other leader lines until cleared');
await page.evaluate(()=>{atlas.setGroup('n');atlas.select('v2');});await page.locator('#detail-meta button',{hasText:'圓孔'}).click();
await page.locator('#detail-meta button',{hasText:'放大'}).click();assert.ok(await page.evaluate(()=>atlas.camera.zoom>=4.5));pass('Zoom-to-structure button');
await page.click('[data-view="f"]');assert.ok(await page.evaluate(()=>atlas.meshes.find(m=>m.name==='Frontal bone').material.clippingPlanes?.length===1));await page.locator('#section-panel summary').click();await page.locator('#cut-y').uncheck();assert.ok(await page.evaluate(()=>!atlas.meshes.find(m=>m.name==='Frontal bone').material.clippingPlanes));pass('Horizontal skull cut toggles');
await page.locator('#cut-x').check();assert.equal(await page.evaluate(()=>{const m=atlas.meshes.find(m=>m.userData.category==='cortex');return m.material.clippingPlanes?.[0].normal.x;}),1);
await page.locator('#cut-x-flip').click();assert.equal(await page.evaluate(()=>atlas.meshes.find(m=>m.userData.category==='cortex').material.clippingPlanes[0].normal.x),-1);
await page.locator('#cut-z').check();assert.equal(await page.evaluate(()=>atlas.meshes.find(m=>m.userData.category==='nerve').material.clippingPlanes.length),2);
await page.locator('#cut-x-all').uncheck();assert.equal(await page.evaluate(()=>[atlas.meshes.find(m=>m.userData.category==='nerve').material.clippingPlanes.length,atlas.meshes.find(m=>m.name==='Frontal bone').material.clippingPlanes.length].join()),'1,2');
await page.locator('#cut-x').uncheck();await page.locator('#cut-z').uncheck();pass('Sagittal and coronal sections, flip side, and brain/nerve scope');
await page.click('[data-view="c"]');assert.ok(await page.evaluate(()=>atlas.meshes.find(m=>m.name==='Cavernous sinus.l').material.clippingPlanes?.[0].normal.z===-1));pass('Cavernous theme uses coronal section on all meshes');
await page.locator('#guides').uncheck();assert.equal(await page.evaluate(()=>atlas.meshes.filter(m=>m.userData.schematic&&m.visible).length),0);await page.locator('#guides').check();await page.locator('#right').uncheck();assert.equal(await page.evaluate(()=>atlas.meshes.filter(m=>/\.r\d*$/.test(m.name)&&m.visible).length),0);await page.locator('#right').check();pass('Schematic and right-side toggles');
await page.click('#notes-button');assert.ok(await page.locator('#notes-dialog').evaluate(e=>e.open));await page.locator('#notes-content [data-go="sof"]').click();assert.equal(await page.evaluate(()=>atlas.state.selected),'sof');pass('Notes dialog jump buttons');
const box=await page.locator('#canvas').boundingBox();const before=await page.evaluate(()=>atlas.camera.position.toArray());await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+120,box.y+box.height/2+40,{steps:6});await page.mouse.up();await page.waitForTimeout(250);const after=await page.evaluate(()=>atlas.camera.position.toArray());await page.waitForTimeout(400);const still=await page.evaluate(()=>atlas.camera.position.toArray());assert.notDeepEqual(before,after);assert.deepEqual(after,still);pass('Drag rotates, no drift after release');
await page.setViewportSize({width:390,height:844});for(const g of Object.keys(info.groups)){await page.click(`[data-view="${g}"]`);const l=await layout();assert.equal(l.overflow,false,g);assert.equal(l.overlaps,0,g);}pass('390px mobile: no horizontal overflow or label overlap');
await page.screenshot({path:'assets/check-mobile.png'});
assert.deepEqual(errors,[]);assert.deepEqual(http,[]);pass('No page errors and no network requests (fully offline)');
report.errors=errors;report.http=http;fs.writeFileSync('assets/verification.json',JSON.stringify(report,null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1);});
