import * as T from 'three';
import {TrackballControls} from 'three/addons/controls/TrackballControls.js';
import {labels,groups,pageTitles} from './labels.js';
import {createSchematics} from './schematic.js';
const $=id=>document.getElementById(id);
const cameras={top:{pos:[0,600,-10],up:[0,0,1],text:'上面觀 · 前方在上 · 左腦在畫面左側'},bottom:{pos:[0,-600,-10],up:[0,0,1],text:'底面觀 · 前方在上 · 左腦在畫面右側'},left:{pos:[600,-10,-10],up:[0,1,0],text:'左側觀 · 前方在畫面左側'},medial:{pos:[-600,-10,-10],up:[0,1,0],text:'由正中面看左半腦 · 前方在畫面右側'},front:{pos:[0,-10,600],up:[0,1,0],text:'前面觀 · 左側在畫面右側'},oblique:{pos:[330,320,420],up:[0,1,0],text:'立體斜視 · 可自由拖曳旋轉'}};
const typeNames={mesh:'原模型構造',guide:'區域導引',schematic:'示意模型',reference:'原圖／層次構造'};
let current='p',names=true,selected=null,language='both',renderer,scene,camera,controls,meshes=[],active=[],width=0,height=0,dirty=true,pageNumber=8,labelSlots=null;
const project=new T.Vector3(),lowerPlane=new T.Plane(new T.Vector3(0,1,0),110);
function decode(s,Ctor){return new Ctor(Uint8Array.from(atob(s),c=>c.charCodeAt(0)).buffer);}
function matches(m,l){return l.models.some(p=>m.name.includes(p)||(m.userData.tags||[]).some(t=>t.startsWith(p)));}
function colorFor(item){const c=item.category,n=item.name;return c==='cortex'?0xcbaab5:c==='cerebellum'?0xbdadb0:c==='stem'?0xb7bcc9:c==='artery'?0xdf6e6e:c==='bone'?0xdbcfaf:c==='nerve'?(n.includes('Oculomotor')||n.includes('oculomotor')?0x83bbef:0xf1d28c):c==='eye'?(n.includes('Sclera')?0xdce5e3:n.includes('Retina')?0xb4bfdd:n.includes('Iris')?0x7b9db2:n.includes('Lens')?0xa9d7e9:0xca8792):n.includes('geniculate')?0xe8c180:n.includes('hypophysis')?0xc29acb:n.includes('ventricle')?0x8cbacd:0xa4b5c1;}
async function initialize(){
 const compressed=Uint8Array.from(atob(window.BRAIN_GZIP),c=>c.charCodeAt(0));const data=await new Response(new Blob([compressed]).stream().pipeThrough(new DecompressionStream('gzip'))).json();
 renderer=new T.WebGLRenderer({canvas:$('canvas'),antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.localClippingEnabled=true;renderer.clippingPlanes=[lowerPlane];renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
 scene=new T.Scene();camera=new T.OrthographicCamera(-180,180,130,-130,.1,2000);scene.add(new T.HemisphereLight(0xececff,0x463e4b,2));for(const [pos,col,intensity] of [[[180,260,280],0xffece6,2.4],[[-180,40,-200],0xb5cdef,1.5],[[0,-220,0],0xfad3cc,1.5]]){const light=new T.DirectionalLight(col,intensity);light.position.set(...pos);scene.add(light);}
 for(const item of data.meshes){const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(decode(item.positions,Float32Array),3));g.setIndex(new T.BufferAttribute(decode(item.indices,Uint32Array),1));g.computeVertexNormals();const col=colorFor(item);const m=new T.Mesh(g,new T.MeshStandardMaterial({color:col,roughness:.68,side:T.DoubleSide}));m.name=item.name;m.userData={category:item.category,baseColor:col,center:item.center,bounds:item.bounds,schematic:false};meshes.push(m);scene.add(m);}
 const schematic=createSchematics();meshes.push(...schematic);scene.add(...schematic);
 for(const l of labels){l.matches=meshes.filter(m=>matches(m,l));l.point=new T.Vector3(...l.position);if(l.representation==='mesh'||['v1','gennari'].includes(l.id)){const left=l.matches.filter(m=>m.name.endsWith('.l')),pool=left.length?left:l.matches;let nearest=null,dist=Infinity;for(const m of pool){let a=m.geometry.attributes.position;for(let i=0;i<a.count;i++){const v=new T.Vector3().fromBufferAttribute(a,i);v.applyMatrix4(m.matrixWorld);let d=v.distanceToSquared(l.point);if(d<dist){dist=d;nearest=v;l.anchorMesh=m;l.localAnchor=new T.Vector3().fromBufferAttribute(a,i);}}}if(nearest)l.point.copy(nearest);}}
 // Presets recreate the screen-relative control frame, including the camera up vector.
 $('total').textContent=labels.length;pageTitles.forEach((title,i)=>{const opt=document.createElement('option');opt.value=i+1;opt.textContent=`${i+1} / 13　${title}`;$('page-select').append(opt);});
 setGroup('p');new ResizeObserver(resize).observe($('stage'));resize();$('loading').hidden=true;renderer.setAnimationLoop(()=>{controls.update();if(dirty){renderer.render(scene,camera);drawLabels();dirty=false;}});
 window.atlas={labels,groups,meshes,scene,camera,get controls(){return controls;},setGroup,select:choose,get state(){return {current,names,selected,pageNumber,active:active.length};}};
}
function setCamera(which){
 const c=cameras[which];controls?.dispose();camera.up.set(...c.up);camera.position.set(...c.pos);camera.zoom=1;camera.lookAt(0,-22,-7);
 controls=new TrackballControls(camera,$('canvas'));controls.target.set(0,-22,-7);controls.staticMoving=true;controls.rotateSpeed=1.35;controls.zoomSpeed=.9;controls.panSpeed=.65;controls.minZoom=.45;controls.maxZoom=5;
 controls.addEventListener('change',()=>dirty=true);controls.addEventListener('start',()=>{$('canvas').classList.add('dragging');$('orientation').textContent='自由視角 · 標點固定於模型；背面構造的指線可穿透表面';controls.handleResize();});controls.addEventListener('end',()=>$('canvas').classList.remove('dragging'));
 controls.update();camera.updateProjectionMatrix();labelSlots=null;$('camera-view').value=which;$('orientation').textContent=c.text;dirty=true;
}
function setGroup(id){current=id;selected=null;$('medial-guide').hidden=id!=='m';const g=groups[id];$('view-title').textContent=g.title;$('view-note').textContent=g.subtitle;$('flow').textContent=names?g.flow:'名稱與說明已隱藏 · 保留項目編號供自測';$('opacity').value=g.opacity;$('right').checked=id!=='m';$('cerebellum').checked=['m','b','a'].includes(id);$('guides').checked=true;$('search').value='';setCamera(g.camera);document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));updateModel();renderList();rebuildLabels();showDetail();}
function updateModel(){const groupLabels=labels.filter(l=>l.groups.includes(current)),sel=labels.find(l=>l.id===selected),outer=+$('opacity').value;const needed=new Set(groupLabels.flatMap(l=>l.matches));if(sel)sel.matches.forEach(m=>needed.add(m));$('opacity-value').textContent=Math.round(outer*100)+'%';
 for(const m of meshes){const cat=m.userData.category,n=m.name,belongs=needed.has(m),highlight=sel?.matches.includes(m);let visible=belongs,opacity=1;
  if(cat==='cortex'){visible=outer>0;opacity=outer;if(highlight){visible=true;opacity=Math.max(outer,.7);}}
  else if(cat==='cerebellum'){visible=$('cerebellum').checked;opacity=current==='m'?.9:.22;}
  else if(cat==='stem'){visible=true;opacity=current==='m'?.85:current==='r'?.14:.23;}
  else if(cat==='deep'){visible=belongs||['Thalamus.l','Thalamus.r'].includes(n);opacity=belongs?.83:.13;if(n.includes('ventricle'))opacity=.25;}
  else if(cat==='eye'){visible=['p','r'].includes(current);opacity=n.includes('Sclera')?.13:n.includes('Retina')?.22:n.includes('Lens')?.55:.85;}
  else if(cat==='bone'){visible=current==='m';opacity=.30;}
  else if(cat==='nerve'){visible=belongs||(current==='b'&&/^Optic/.test(n));opacity=belongs?1:.4;}
  if(m.userData.schematic&&!$('guides').checked)visible=false;
  if(!$('right').checked&&/\.r(?:\d+)?$/.test(n))visible=false;
  if(highlight&&visible)opacity=Math.max(opacity,.72);
  m.visible=visible;m.material.opacity=opacity;m.material.transparent=opacity<.999;m.material.depthWrite=opacity>.7;m.material.color.setHex(current==='m'&&n.startsWith('Calcarine sulcus')?0xffbd32:m.userData.baseColor);m.material.emissive.setHex(highlight?0x624b2d:0);m.material.emissiveIntensity=highlight?.65:0;if(current==='m'&&n.startsWith('Calcarine sulcus')){m.material.emissive.setHex(0xad6200);m.material.emissiveIntensity=.38;}m.renderOrder=opacity<.5?1:0;
 }
 dirty=true;
}
function relevant(){const q=$('search').value.trim().toLowerCase();return q?labels.filter(l=>(l.zh+' '+l.en+' '+(l.pdfNo?'講義 '+l.pdfNo:'')).toLowerCase().includes(q)):labels.filter(l=>l.groups.includes(current));}
function renderList(){const ls=relevant();$('count').textContent=ls.length+' 項';$('list-title').textContent=$('search').value?'跨主題搜尋結果':'本主題構造';$('structure-list').replaceChildren();for(const l of ls){const b=document.createElement('button');b.className='structure'+(selected===l.id?' selected':'');b.dataset.id=l.id;b.innerHTML=`<span class="num">${String(l.number).padStart(2,'0')}</span><div><strong>${names?l.zh:'項目 '+l.number}</strong><small>${names?l.en:'名稱已隱藏'}</small></div><span class="hint">${l.pdfNo?'圖 '+l.pdfNo:'↗'}</span>`;b.onclick=()=>choose(l);$('structure-list').append(b);}if(!ls.length)$('structure-list').innerHTML='<p class="empty">沒有符合的構造。</p>';}
function choose(l){if(typeof l==='string')l=labels.find(x=>x.id===l);if(!l)return;if(!l.groups.includes(current)){const q=$('search').value;setGroup(l.groups[0]);$('search').value=q;}selected=l.id;if(l.representation==='schematic')$('guides').checked=true;if(l.id==='cerebellum')$('cerebellum').checked=true;updateModel();renderList();rebuildLabels();showDetail(l);}
function showDetail(l){$('detail').querySelector('.detail-number').textContent=l?String(l.number).padStart(2,'0'):'◎';$('detail').querySelector('h3').innerHTML=l?(names?`${l.zh}<small>${l.en}</small>`:`項目 ${l.number} · 名稱已隱藏`):(names?'點選構造，追蹤它的位置。':'名稱已全部隱藏');$('detail').querySelector('p').textContent=l?(names?l.note:'可旋轉與點選編號。按「顯示所有名稱」揭曉名稱與說明。'):(names?'實線為原模型構造；虛線是區域或路徑示意。指線可穿透表面，旋轉時請注意前後關係。':'模型標籤、側欄、路徑文字及說明同步遮蔽。');$('detail-meta').replaceChildren();if(l){const badge=document.createElement('span');badge.textContent=typeNames[l.representation]+(l.extra?' · 補充背景':'')+(l.pdfNo?' · 原圖第 '+l.pdfNo+' 號':'');$('detail-meta').append(badge);for(const p of l.pages){const b=document.createElement('button');b.textContent='PDF '+p;b.onclick=()=>openPage(p);$('detail-meta').append(b);}}}
function labelHTML(l){const no=`<b>${String(l.number).padStart(2,'0')}</b>`;return !names?no:`${no}<div>${language!=='en'?`<div class="zh">${l.zh}</div>`:''}${language!=='zh'?`<div class="en">${l.en}</div>`:''}</div>`;}
function focusLeader(id){
 $('leaders').classList.toggle('has-focus',!!id);
 for(const o of active){const focus=o.l.id===id;o.group.classList.toggle('focused',focus);o.el.classList.toggle('traced',focus);o.dot.setAttribute('r',focus?5:3.6);if(focus)$('leaders').append(o.group);}
}
function rebuildLabels(){
 const ls=labels.filter(l=>l.groups.includes(current));$('labels').replaceChildren();$('leaders').replaceChildren();
 const svg=name=>document.createElementNS('http://www.w3.org/2000/svg',name);
 active=ls.map(l=>{const el=document.createElement('button');el.className='label '+(l.representation==='mesh'?'':'guide')+(selected===l.id?' selected':'');el.dataset.id=l.id;el.innerHTML=labelHTML(l);el.setAttribute('aria-label',names?l.zh:'項目 '+l.number);el.onclick=()=>choose(l);el.onpointerenter=()=>focusLeader(l.id);el.onpointerleave=()=>focusLeader(selected);el.onfocus=()=>focusLeader(l.id);el.onblur=()=>focusLeader(selected);$('labels').append(el);
 const group=svg('g'),halo=svg('line'),line=svg('line'),dot=svg('circle');group.dataset.id=l.id;halo.classList.add('leader-halo');line.classList.add('leader-main');line.classList.toggle('guide',l.representation!=='mesh');dot.setAttribute('r',3.6);group.append(halo,line,dot);$('leaders').append(group);return {l,el,group,halo,line,dot};});focusLeader(selected);resize();
}
function resize(){const mobile=innerWidth<=700;const maxRows=Math.ceil(active.length/2);$('stage').style.minHeight=mobile?Math.max(480,maxRows*51+46)+'px':Math.max(440,maxRows*44+40)+'px';const r=$('stage').getBoundingClientRect();width=r.width;height=r.height;$('leaders').setAttribute('viewBox',`0 0 ${width} ${height}`);if(!renderer)return;renderer.setSize(width,height,false);controls?.handleResize();const half=width<500?height*.57:130;camera.left=-half*width/height;camera.right=half*width/height;camera.top=half;camera.bottom=-half;camera.updateProjectionMatrix();dirty=true;}
function drawLabels(){
 if(!width||!camera)return;camera.updateMatrixWorld();
 const entries=active.map(o=>{if(o.l.anchorMesh)o.l.point.copy(o.l.localAnchor).applyMatrix4(o.l.anchorMesh.matrixWorld);project.copy(o.l.point).project(camera);return {...o,x:(project.x+1)*width/2,y:(1-project.y)*height/2,z:project.z};});
 // Keep labels in fixed slots as the brain rotates, so names do not jump across the screen.
 if(!labelSlots){const sorted=[...entries].sort((a,b)=>a.x-b.x),mid=Math.ceil(sorted.length/2);labelSlots=[sorted.slice(0,mid),sorted.slice(mid)].map(a=>a.sort((a,b)=>a.y-b.y).map(o=>o.l.id));}
 const byId=new Map(entries.map(o=>[o.l.id,o]));
 for(let side=0;side<2;side++){const arr=labelSlots[side].map(id=>byId.get(id));const sizes=arr.map(o=>o.el.offsetHeight||34),total=sizes.reduce((a,b)=>a+b,0)+9*(arr.length-1);let y=Math.max(9,(height-total)/2);
 for(let i=0;i<arr.length;i++){const o=arr[i],w=o.el.offsetWidth,x=side?width-w-5:5;o.el.style.transform=`translate(${x}px,${y}px)`;const onscreen=o.z>-1&&o.z<1&&o.x>=0&&o.x<=width&&o.y>=0&&o.y<=height;o.group.style.display=onscreen?'':'none';o.el.classList.toggle('offscreen',!onscreen);
 for(const line of [o.halo,o.line]){line.setAttribute('x1',side?x:x+w);line.setAttribute('y1',y+sizes[i]/2);line.setAttribute('x2',o.x);line.setAttribute('y2',o.y);}o.dot.setAttribute('cx',o.x);o.dot.setAttribute('cy',o.y);y+=sizes[i]+9;}}
}
function toggleNames(show){names=show;document.body.classList.toggle('hidden-names',!show);$('hide').setAttribute('aria-pressed',!show);$('show').setAttribute('aria-pressed',show);if(!show){$('reference-dialog').close();$('notes-dialog').close();$('source-dialog').close();}$('flow').textContent=show?groups[current].flow:'名稱與說明已隱藏 · 保留項目編號供自測';renderList();rebuildLabels();showDetail(labels.find(l=>l.id===selected));}
function openPage(p){if(!names){$('detail').querySelector('p').textContent='原圖包含答案。請先按「顯示所有名稱」，再開啟原圖。';return;}pageNumber=Math.max(1,Math.min(13,p));$('page-select').value=pageNumber;$('reference-img').src=window.REFERENCE_IMAGES?.[pageNumber]||`assets/page-${String(pageNumber).padStart(2,'0')}.png`;$('prev-page').disabled=pageNumber===1;$('next-page').disabled=pageNumber===13;if(!$('reference-dialog').open)$('reference-dialog').showModal();}
function showNotes(){if(!names){$('detail').querySelector('p').textContent='講義重點含答案，請先顯示所有名稱。';return;}$('notes-content').innerHTML=`<h3>視放射的上下視野</h3><p>顳葉的 Meyer’s loop 傳遞對側上方視野；頂葉的上方視放射傳遞對側下方視野。下半部視網膜對應上方視野。講義第 9 頁兩題因此分別為 D（顳葉視放射）與 D（僅②）。</p><h3>近反射三件事</h3><p>雙側內直肌收縮使眼球會聚；睫狀肌收縮使水晶體變厚；瞳孔括約肌收縮使瞳孔縮小。動眼神經包含體運動與副交感傳出成分，副交感路徑須在睫狀神經節中繼。</p><h3>第 6 頁題目整理</h3><p>左欄：前脈絡叢動脈敘述的錯誤為「殼核主要由 AChA 供血」；非 ICA 直接分支者為前交通動脈；AChA 通常直接起自 ICA。</p><p>右欄：左側單眼全盲題選「僅②」（B，左側眼動脈瘤壓迫左視神經的題設）；LGN 血供題在所列選項中選「僅③」（C，AChA）；視覺皮質供血題選「僅③」（D，PCA）。這些是題目選項下的判讀，不表示 LGN 只接受一條動脈供血，也不把所有動脈瘤都等同特定視野缺損。</p><h3>內囊與 AChA</h3><p>AChA 可參與內囊後肢、視徑、LGN 與脈絡叢的供血。內囊與基底核亦有豆紋動脈等來源，個體供血範圍存在變異。講義第 7 頁病例是教學案例，3D 高亮只呈現解剖鄰近關係，沒有建立個人病灶模型。</p><h3>標號注意</h3><p>側欄的「圖 1–10」對應第 8／10 頁。第 6 號原圖未具名；第 12／13 頁標本上的 1–18 沒有完整答案表，維持未判定。題目解說是本頁補充整理，原頁沒有列出的答案不冒充原講義答案。</p><p>參考：<a href="https://nba.uth.tmc.edu/Assets/pdf/courses/ns_2013_lab_guide.v13.1.0_SCR.pdf" target="_blank" rel="noopener">UTHealth 神經解剖實驗教材</a>、<a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC7973945/" target="_blank" rel="noopener">AChA 解剖研究</a>與使用者原 PDF。</p>`;$('notes-dialog').showModal();}
$('calcarine-focus').onclick=()=>{setCamera('medial');$('right').checked=false;$('opacity').value=1;const target=labels.find(l=>l.id==='calcarine').point;camera.position.add(new T.Vector3().subVectors(target,controls.target));controls.target.copy(target);camera.zoom=1.65;camera.updateProjectionMatrix();controls.update();choose('calcarine');};$('gennari-original').onclick=()=>openPage(12);
$('hide').onclick=()=>toggleNames(false);$('show').onclick=()=>toggleNames(true);$('views').onclick=e=>{let b=e.target.closest('[data-view]');if(b)setGroup(b.dataset.view);};$('search').oninput=renderList;$('reset').onclick=()=>setGroup(current);$('camera-view').onchange=()=>setCamera($('camera-view').value);$('opacity').oninput=updateModel;for(const id of ['right','cerebellum','guides'])$(id).onchange=updateModel;$('language').onchange=()=>{language=$('language').value;rebuildLabels();};$('clear').onclick=()=>{selected=null;updateModel();renderList();rebuildLabels();showDetail();};$('reference').onclick=()=>openPage(groups[current].pages[0]);$('page-select').onchange=()=>openPage(+$('page-select').value);$('prev-page').onclick=()=>openPage(pageNumber-1);$('next-page').onclick=()=>openPage(pageNumber+1);$('source-button').onclick=()=>$('source-dialog').showModal();$('notes-button').onclick=showNotes;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
initialize().catch(e=>{$('loading').textContent='模型載入失敗：'+e.message+'。請使用新版 Chrome 或 Edge 開啟。';console.error(e);});
