// Entries transcribed from the 13-page supplied PDF; extra context is explicitly marked.
// Models are Z-Anatomy object name prefixes. Positions are mm: left +X, superior +Y, anterior +Z.
const rows=[];
function add(id,zh,en,groups,pages,models,position,note,representation='mesh',pdfNo=null,extra=false){rows.push({id,zh,en,groups:groups.split(''),pages,models,position,note,representation,pdfNo,extra});}
add('optic-nerve','視神經','Optic nerve (CN II)','pr',[8,10,11],['Optic nerve (II)'],[18,-39,40],'將視網膜訊號傳入顱內；此段位於視交叉之前。','mesh',1);
add('lgn','外側膝狀體核','Lateral geniculate nucleus (LGN)','pbdr',[6,8,10,11],['Lateral geniculate body'],[19,-28,-13],'視徑主要的丘腦中繼站；之後經視放射投射到初級視覺皮質。原模型使用 lateral geniculate body 名稱。','mesh',2);
add('optic-radiation','視放射','Optic radiation','pr',[8,9,10,11],['guide:radiation'],[36,-15,-47],'連接 LGN 與枕葉 V1；彩色束線為依解剖關係繪製的路徑示意，不是擴散 MRI 纖維追蹤。','schematic',3);
add('v1','初級視覺皮質／紋狀皮質','Primary visual / striate cortex (V1)','pmr',[8,10,11,12],['Calcarine sulcus','Cuneus','Lingual gyrus'],[8,-23,-79],'主要位於距狀溝兩岸，對應 Brodmann area 17。高亮以相鄰表面區域導引，不代表已精確分割的 V1 邊界。','guide',4);
add('association','視覺聯合皮質','Visual association cortex','pr',[8,10],['Lateral occipital gyrus','Superior occipital gyri'],[30,-16,-81],'位於初級視覺皮質周圍及相關視覺處理網路；此處標示枕葉周邊的範圍導引。','guide',5);
add('midbrain-six','第 6 號：中腦核群區（未具名）','Unlabelled midbrain region, figure no. 6','r',[8,10],['Nucleus of oculomotor nerve','Accessory nucleus of oculomotor nerve'],[0,-33,-9],'講義第 6 號箭頭指向彩色中腦核群，但沒有寫出名稱。旁列動眼神經核與 EW 核作為補充；不將本推定當成原講義正式答案。','guide',6);
add('cn3','動眼神經','Oculomotor nerve (CN III)','r',[8,10],['Oculomotor nerve (III)'],[13,-42,20],'近反射的傳出神經：運動成分參與內直肌收縮，副交感成分經睫狀神經節到眼內肌。','mesh',7);
add('medial-rectus','內直肌','Medial rectus muscle','r',[8,10],['Medial rectus muscle'],[18,-47,54],'雙側內直肌收縮使眼球向內轉，形成會聚。','mesh',8);
add('ciliary-muscle','睫狀肌','Ciliary muscle','r',[8,10],['guide:ciliary'],[36,-49,69],'收縮時使懸韌帶張力減少，水晶體變厚以看近；本頁使用環形位置示意，非肌纖維模型。','schematic',9);
add('sphincter','瞳孔括約肌','Sphincter pupillae','r',[8,10],['guide:sphincter'],[31,-49,74],'近反射中收縮使瞳孔縮小；薄環只示意肌肉所在位置與收縮方向。','schematic',10);
add('chiasm','視交叉','Optic chiasm','pmr',[9,11,13],['Optic chiasm'],[0,-28,17],'鼻側視網膜纖維在此交叉，顳側纖維保持同側；因此每側視徑攜帶對側視野。');
add('optic-tract','視徑','Optic tract','pr',[11],['Optic tract'],[16,-28,0],'視交叉之後通往 LGN 的路徑；與視交叉前的視神經區分。');
add('meyer','梅氏環（顳葉視放射）',"Meyer’s loop / temporal optic radiation",'p',[9,11],['guide:meyer'],[34,-31,3],'先向前繞過側腦室顳角，再向後到距狀溝下岸；傳遞對側上方視野。損傷可造成對側上象限盲（pie in the sky）。','schematic');
add('baum','鮑氏環（頂葉視放射）',"Baum’s loop / parietal optic radiation",'p',[9,11],['guide:baum'],[31,-3,-45],'講義用 Baum’s loop 指上方／頂葉視放射；通向距狀溝上岸，傳遞對側下方視野。此束線為走向示意。','schematic');
add('retina','視網膜','Retina','pr',[8,9],['Retina'],[34,-49,53],'影像上下與左右皆倒置；下半部視網膜對應上方視野。','mesh',null,true);
add('calcarine','距狀溝','Calcarine sulcus','m',[12],['Calcarine sulcus'],[6,-22,-67],'枕葉內側面的重要溝；初級視覺皮質分布在其上下兩岸。');
add('parieto-occipital','頂枕溝','Parieto-occipital sulcus','m',[12],['Parieto-occipital sulcus'],[6,10,-60],'腦內側面區分頂葉與枕葉的重要界線。');
add('gennari','Gennari 線／紋','Line / stria of Gennari','m',[12],['Calcarine sulcus'],[8,-25,-75],'V1 皮質內富含髓鞘的纖維帶，屬切面／組織層次構造。本 3D 表面未逐層建模；標點只提示 V1 區域，請看第 12 頁局部照片。','reference');
add('pituitary','腦下垂體','Pituitary gland / hypophysis','m',[13],['Adenohypophysis','Neurohypophysis'],[0,-39,17],'位於蝶鞍內，視交叉在其上方；本模型保留前葉及後葉。');
add('sella','蝶鞍','Sella turcica','m',[13],['Sphenoid bone'],[0,-44,20],'蝶骨中央的鞍形區域，容納腦下垂體。高亮整個蝶骨時，標點才是蝶鞍位置。','guide');
add('ica','頸內動脈','Internal carotid artery (ICA)','b',[3,4,5,6],['Internal carotid artery'],[14,-38,20],'前循環的重要來源；講義列出 ACA、MCA、眼動脈與前脈絡叢動脈等分支。此視圖只顯示近顱底部分。');
add('aca','前大腦動脈','Anterior cerebral artery (ACA)','ba',[3,4,5,6],['Anterior cerebral artery'],[6,-28,29],'源自頸內動脈；左右 ACA 由前交通動脈相連。');
add('mca','中大腦動脈','Middle cerebral artery (MCA)','ba',[3,4,5,6,7],['Middle cerebral artery','Insular branches of middle cerebral artery','Temporal branches of middle cerebral artery','Parietal branches of middle cerebral artery'],[26,-30,22],'源自頸內動脈，向外側走行；MCA 本身不構成 Willis 環的封閉環路。');
add('ophthalmic','眼動脈','Ophthalmic artery','b',[3,5,6],['Ophthalmic artery'],[15,-39,39],'頸內動脈的分支，供應眼眶與眼部結構；視網膜中央動脈是其分支。');
add('acha','前脈絡叢動脈','Anterior choroidal artery (AChA)','bad',[4,5,6,7],['guide:acha'],[14,-32,1],'通常由頸內動脈發出；供應視徑、LGN、內囊後肢與脈絡叢等部分區域，供血範圍有變異。原 atlas 未含可用獨立網格，本頁為走向示意。','schematic');
add('acom','前交通動脈','Anterior communicating artery (ACom)','b',[3,4,6],['Anterior communicating artery'],[0,-30,23],'連接左右前大腦動脈；不是頸內動脈直接分出的另一條平行主幹。');
add('pcom','後交通動脈','Posterior communicating artery (PCom)','b',[3,4],['Posterior communicating artery'],[8,-35,15],'連接頸內動脈循環與後大腦動脈循環，構成 Willis 環的側後部。');
add('pca','後大腦動脈','Posterior cerebral artery (PCA)','ba',[3,4,6],['Posterior cerebral artery','Medial occipital artery','Lateral occipital artery','Parieto-occipital artery'],[26,-25,-27],'通常由基底動脈分出，繞行中腦後到枕葉；為視覺皮質的重要供血來源。');
add('basilar','基底動脈','Basilar artery','ba',[3,4],['Basilar artery'],[0,-50,3],'由左右椎動脈匯合形成，沿橋腦腹側上行。');
add('vertebral','椎動脈','Vertebral artery','ba',[3,4],['Vertebral artery'],[12,-77,-13],'後循環來源；左右椎動脈匯合為基底動脈。');
add('willis','威利氏環','Cerebral arterial circle / Circle of Willis','b',[3,4],['Anterior communicating artery','Anterior cerebral artery','Posterior communicating artery','Posterior cerebral artery','Internal carotid artery'],[0,-32,10],'前交通、左右 ACA 近端、ICA 末端、後交通與 PCA 近端共同形成環路。高亮保留血管全長，並非每一段都屬於環本身。','guide');
add('medial-orbitofrontal','內側眶額動脈','Medial orbitofrontal artery','a',[4,5],['Orbitofrontal branches of anterior cerebral artery'],[8,-22,56],'圖中額葉底面的 ACA 分支。原 atlas 對應眶額分支網格。');
add('heubner','Heubner 回返動脈','Recurrent artery of Heubner','a',[4,5],['guide:heubner'],[10,-26,25],'又稱內側紋狀體動脈，常從 ACA 的近端分出後回返。此處以短支線示意。','schematic');
add('lenticulostriate','內、外側豆紋動脈','Medial and lateral lenticulostriate arteries','ad',[4,5,7],['Proximal lateral striate branches','Distal lateral striate branches','guide:heubner'],[18,-24,24],'原模型具外側紋狀體分支；內側群以回返動脈導引補充。勿將整個基底核都歸為 AChA 單獨供血。','guide');
add('lateral-orbitofrontal','外側眶額動脈','Lateral orbitofrontal artery','a',[4,5],['guide:lateral-orbitofrontal'],[37,-22,39],'MCA 系統在眶額區的分支，本頁為位置與分支走向示意。','schematic');
add('ascending-frontal','上行額動脈（燭臺分支）','Ascending frontal / candelabra artery','a',[4,5],['guide:ascending-frontal'],[48,1,23],'講義圖中標示的額葉上行分支；此處不聲稱重建個體的真實分支變異。','schematic');
add('sca','上小腦動脈','Superior cerebellar artery (SCA)','a',[4,5],['Superior cerebellar artery'],[23,-42,-28],'通常源自基底動脈遠端，供應小腦上部。');
add('pontine','橋腦動脈','Pontine arteries','a',[4,5],['Medial pontine branches of basilar artery','Lateral pontine branches of basilar artery'],[7,-49,4],'從基底動脈發出的內側與外側橋腦分支。');
add('labyrinthine','內耳／迷路動脈','Internal acoustic / labyrinthine artery','a',[4,5],['guide:labyrinthine'],[27,-57,-3],'圖中內耳供血分支；常由 AICA 發出，也存在變異。本頁為路徑示意。','schematic');
add('aica','前下小腦動脈','Anterior inferior cerebellar artery (AICA)','a',[4,5],['Anterior inferior cerebellar artery'],[18,-60,-13],'通常來自基底動脈，走向小腦前下部。');
add('asa','前脊髓動脈','Anterior spinal artery','a',[4,5],['Anterior spinal artery'],[0,-87,-16],'左右來源分支在腹側形成前脊髓動脈系統；頁面只保留上段。');
add('pica','後下小腦動脈','Posterior inferior cerebellar artery (PICA)','a',[4,5],['Posterior inferior cerebellar artery'],[27,-64,-43],'通常由椎動脈發出。講義圖片以 cut 表示切斷的血管端，非另一種血管。');
add('psa','後脊髓動脈','Posterior spinal artery','a',[4,5],['guide:psa'],[6,-88,-31],'位於脊髓後方的成對供血系統；此處只有上段位置示意。','schematic');
add('posterior-choroidal','後脈絡叢動脈','Posterior choroidal arteries','d',[6],['guide:posterior-choroidal'],[14,-20,-25],'講義題目中提及的後循環分支；本頁以 PCA 到脈絡叢附近的路徑作導引。','schematic');
add('lateral-ventricle','側腦室','Lateral ventricle','d',[6],['Lateral ventricle'],[23,-10,-36],'內含腦脊髓液的腔室；可用半透明外形觀察與視放射的鄰近關係。');
add('plexus','脈絡叢','Choroid plexus','d',[6],['Choroid plexus'],[25,-18,-14],'腦室內產生腦脊髓液的組織；勿與 choroid（眼球脈絡膜）混淆。');
add('internal-capsule','內囊','Internal capsule','d',[6,7],['guide:internal-capsule'],[15,-12,6],'位於尾狀核／丘腦與豆狀核之間的白質通道；本模型以帶狀導引表示，非完整白質分割。','schematic');
add('anterior-limb','內囊前肢','Anterior limb of internal capsule','d',[7],['guide:anterior-limb'],[12,-8,22],'位於尾狀核頭與豆狀核之間。','schematic');
add('genu','內囊膝','Genu of internal capsule','d',[7],['guide:genu'],[13,-12,11],'內囊前、後肢轉折處；圖中以運動通路示意其功能關聯。','schematic');
add('posterior-limb','內囊後肢','Posterior limb of internal capsule','d',[6,7],['guide:posterior-limb'],[17,-14,-2],'位於丘腦與豆狀核之間；AChA 可供應其中部分區域，亦有其他穿通支參與。','schematic');
add('sublenticular','內囊豆狀核下部','Sublenticular part of internal capsule','d',[7],['guide:sublenticular'],[24,-25,0],'位於豆狀核下方；視放射顳葉部分與此區相鄰。','schematic');
add('retrolenticular','內囊豆狀核後部','Retrolenticular part of internal capsule','d',[7],['guide:retrolenticular'],[26,-13,-18],'位於豆狀核後方，與視放射通過的區域相關。','schematic');
add('putamen','殼核','Putamen','d',[6,7],['Putamen'],[27,-10,7],'基底核的一部分；與蒼白球共同組成豆狀核。');
add('lentiform','豆狀核','Lentiform nucleus','d',[7],['Putamen','Globus pallidus'],[26,-12,6],'由殼核與蒼白球構成；圖中的 lenticular nucleus 與 lentiform nucleus 為同一組合名稱。');
add('caudate','尾狀核頭','Head of caudate nucleus','d',[7],['Caudate nucleus'],[10,-3,25],'原網格包含整條尾狀核；標點指向頭部，不能把全部高亮都當成尾狀核頭。','guide');
add('thalamus','丘腦','Thalamus','dm',[7],['Thalamus'],[12,-14,-8],'多條感覺傳導的中繼區；LGN 位於其後外側的相關區域。');
add('mgn','內側膝狀體','Medial geniculate body','d',[7],['Medial geniculate body'],[14,-28,-13],'主要與聽覺傳導相關；和視覺的外側膝狀體區分。');
add('corona','放射冠','Corona radiata','d',[7],['guide:corona'],[18,10,2],'由大腦皮質向內囊匯聚的扇狀白質；此處以路徑示意表示。','schematic');
add('corticospinal','皮質脊髓徑','Corticospinal tract','d',[7],['guide:corticospinal'],[16,-15,0],'講義以通過內囊的運動路徑說明臨床關聯；本頁只示意顱內段。','schematic');
add('corticobulbar','皮質延腦徑／皮質核徑','Corticobulbar / corticonuclear tract','d',[7],['guide:corticobulbar'],[12,-17,9],'從皮質投射到腦幹運動核的通路；示意線並不表示每條纖維的精確位置。','schematic');
add('motor-cortex','體運動皮質','Somatomotor cortex','d',[7],['Precentral gyrus'],[36,30,-4],'圖中運動下行通路的皮質起點；以中央前回作位置對照。');
add('nucleus3','動眼神經核','Oculomotor nucleus','r',[8],['Nucleus of oculomotor nerve'],[2,-34,-9],'近反射補充：支配內直肌等眼外肌的體運動核。不是原圖第 6 號的已確認答案。','mesh',null,true);
add('ew','動眼神經副核（EW 核）','Edinger–Westphal nucleus','r',[8],['Accessory nucleus of oculomotor nerve'],[1,-31,-9],'近反射補充：眼副交感傳出相關核群；其節前纖維隨 CN III 到睫狀神經節。','mesh',null,true);
add('ciliary-ganglion','睫狀神經節','Ciliary ganglion','r',[8],['guide:ganglion'],[30,-49,49],'近反射補充：副交感節前、節後神經元的中繼站；此處用小球示意所在位置，大小不代表量測值。','schematic',null,true);
add('lens','水晶體','Lens','r',[8],['Lens'],[31,-49,71],'近反射的調節部分：水晶體變厚，使屈光力增加。');
add('callosum','胼胝體','Corpus callosum','m',[12,13],['Corpus callosum'],[0,5,0],'內側面定位用補充構造；原照片上的數字未附完整對照表，因此不指派照片數字。','mesh',null,true);
add('midbrain','中腦','Midbrain','m',[8,12,13],['Midbrain'],[0,-36,-9],'腦幹上部；提供近反射核群與視徑周圍的位置背景。','mesh',null,true);
add('pons','橋腦','Pons','m',[4,12,13],['Pons'],[0,-53,-5],'腦幹中部，腹側可見基底動脈。','mesh',null,true);
add('medulla','延腦','Medulla oblongata','m',[4,12,13],['Medulla oblongata'],[0,-78,-16],'腦幹下部，與椎動脈及脊髓相鄰。','mesh',null,true);
add('cerebellum','小腦','Cerebellum','m',[4,12,13],['Tonsil of cerebellum','semilunar lobule','quadrangular lobule','Gracile lobule','Biventral lobule','Culmen','Declive'],[25,-56,-44],'提供腦底與內側面的空間背景；可切換顯示以看清深部血管。','mesh',null,true);
export const labels=rows.map((r,i)=>({...r,number:i+1}));
export const groups={p:{title:'視覺路徑',subtitle:'從眼到枕葉，沿著同一條訊號路徑看空間關係',pages:[8,9,10,11,12],camera:'top',opacity:.11,flow:'視網膜 → 視神經 → 視交叉 → 視徑 → LGN → 視放射 → V1'},b:{title:'腦底血管',subtitle:'前、後循環與 Willis 環',pages:[3,4,5,6],camera:'bottom',opacity:.17,flow:'前循環：頸內動脈　｜　後循環：椎動脈 → 基底動脈 → 後大腦動脈'},a:{title:'血管分支',subtitle:'對照講義腦底血供圖的細部標示',pages:[4,5],camera:'bottom',opacity:.10,flow:'實體血管採原模型網格；缺少的細分支以淡紫色示意線補充'},r:{title:'近反射',subtitle:'會聚、調節、縮瞳 · 保留講義第 1–10 號對照',pages:[8,10],camera:'top',opacity:.07,flow:'會聚：內直肌　｜　調節：睫狀肌與水晶體　｜　縮瞳：瞳孔括約肌'},m:{title:'腦內側面',subtitle:'保留左半腦，從正中面觀察枕葉與蝶鞍關係',pages:[12,13],camera:'medial',opacity:1,flow:'距狀溝與 V1　｜　視交叉位於腦下垂體上方'},d:{title:'深部構造',subtitle:'內囊、基底核及前脈絡叢動脈的鄰近關係',pages:[6,7],camera:'top',opacity:.05,flow:'原模型深部核團＋白質位置示意；供血範圍不是僅由一條血管完全決定'}};
export const pageTitles=['課程封面','血管課程標題','Willis 環與前後循環','腦底血管完整圖','頸內動脈分支','血供相關考題','內囊與臨床關聯','近反射編號 1–10','視放射與視野題目','近反射／標本對照','視覺路徑標本標示','內側面：V1 與距狀溝','視交叉、腦下垂體與蝶鞍'];
