const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const {pathToFileURL}=require('node:url');const path=require('node:path');
(async()=>{const browser=await chromium.launch(fs.existsSync('/opt/pw-browsers/chromium')?{headless:true,executablePath:'/opt/pw-browsers/chromium',args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}:{channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1100},offline:true});const page=await context.newPage();const errors=[],http=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))http.push(r.url())});await page.goto(pathToFileURL(path.resolve('腦與視覺路徑3D.html')).href);await page.waitForFunction(()=>window.atlas,{timeout:90000});const report={date:new Date().toISOString(),browser:await browser.version(),offline:true,checks:[]};
const pass=x=>report.checks.push(x);assert.equal(await page.evaluate(()=>atlas.labels.length),70);assert.equal(await page.evaluate(()=>atlas.labels.filter(l=>l.matches.length===0).length),0);pass('70 entries with model or guide matches');
const groupCounts={p:10,b:12,a:18,r:17,m:13,d:21};
async function layout(){for(let i=0;i<3;i++)await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.waitForTimeout(180);return await page.evaluate(()=>{const stage=document.querySelector('#stage').getBoundingClientRect(),rs=[...document.querySelectorAll('.label')].map(e=>e.getBoundingClientRect()),pairs=[];for(let i=0;i<rs.length;i++)for(let j=i+1;j<rs.length;j++)if(Math.min(rs[i].right,rs[j].right)-Math.max(rs[i].left,rs[j].left)>1&&Math.min(rs[i].bottom,rs[j].bottom)-Math.max(rs[i].top,rs[j].top)>1)pairs.push([i,j]);return{overlaps:pairs,outside:rs.filter(r=>r.left<stage.left-1||r.right>stage.right+1||r.top<stage.top-1||r.bottom>stage.bottom+1).length,overflow:document.documentElement.scrollWidth>innerWidth}});}
for(const [g,count]of Object.entries(groupCounts)){await page.click(`[data-view="${g}"]`);assert.equal(await page.locator('.label').count(),count);assert.deepEqual(await layout(),{overlaps:[],outside:0,overflow:false});await page.locator('.structure').first().click();await page.click('#hide');assert.equal(await page.locator('.label .zh,.label .en').count(),0);assert.ok((await page.locator('#structure-list').innerText()).includes('名稱已隱藏'));assert.ok((await page.locator('#detail h3').innerText()).includes('名稱已隱藏'));await page.click('#reference');assert.equal(await page.locator('#reference-dialog').evaluate(e=>e.open),false);await page.click('#notes-button');assert.equal(await page.locator('#notes-dialog').evaluate(e=>e.open),false);await page.click('#show');assert.equal(await page.locator('.label .zh').count(),count);}pass('All six themes: counts, labels in bounds, no overlaps, hide/show and reference answer guard');
await page.locator('#search').fill('Meyer');assert.equal(await page.locator('.structure').count(),1);await page.locator('.structure').click();assert.equal(await page.evaluate(()=>atlas.state.current),'p');pass('Cross-theme bilingual search and selection');await page.locator('#search').fill('');
await page.locator('#guides').uncheck();assert.equal(await page.evaluate(()=>atlas.meshes.filter(m=>m.userData.schematic&&m.visible).length),0);await page.locator('#guides').check();assert.ok(await page.evaluate(()=>atlas.meshes.some(m=>m.userData.schematic&&m.visible)));await page.locator('#right').uncheck();assert.equal(await page.evaluate(()=>atlas.meshes.filter(m=>/\.r(?:\d+)?$/.test(m.name)&&m.visible).length),0);await page.locator('#opacity').fill('0');assert.equal(await page.evaluate(()=>atlas.meshes.filter(m=>m.userData.category==='cortex'&&m.visible).length),0);pass('Schematic toggle, hemisphere removal, cortex opacity');
await page.click('#reset');const q=await page.evaluate(()=>atlas.camera.position.toArray());const box=await page.locator('#canvas').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+90,box.y+box.height/2+55,{steps:8});await page.mouse.up();await page.waitForTimeout(400);assert.notDeepEqual(await page.evaluate(()=>atlas.camera.position.toArray()),q);await page.mouse.wheel(0,-200);await page.waitForTimeout(350);assert.ok(await page.evaluate(()=>atlas.camera.zoom>1));pass('Pointer drag rotation and wheel zoom');
await page.locator('#language').selectOption('en');assert.equal(await page.locator('.label .zh').count(),0);await page.locator('#language').selectOption('zh');assert.equal(await page.locator('.label .en').count(),0);await page.locator('#language').selectOption('both');
await page.click('#reference');for(let i=1;i<=13;i++){await page.locator('#page-select').selectOption(''+i);await page.waitForFunction(()=>{let e=document.querySelector('#reference-img');return e.complete&&e.naturalWidth>0});assert.ok((await page.locator('#reference-img').getAttribute('src')).startsWith('data:image/png;base64,'));}assert.equal(await page.locator('#next-page').isDisabled(),true);await page.locator('#prev-page').click();assert.equal(await page.locator('#page-select').inputValue(),'12');await page.click('[data-close="reference-dialog"]');pass('Three language modes and all 13 embedded lecture pages decode offline');
await page.click('[data-view="p"]');await page.screenshot({path:'assets/preview-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});for(const g of Object.keys(groupCounts)){await page.click(`[data-view="${g}"]`);assert.deepEqual(await layout(),{overlaps:[],outside:0,overflow:false});}await page.click('[data-view="p"]');await page.screenshot({path:'assets/preview-mobile.png',fullPage:true});await page.click('#hide');assert.equal(await page.locator('.label .zh').count(),0);await page.click('#show');assert.equal(await page.locator('.label .zh').count(),10);pass('390px mobile: all themes fit, no overlapping labels, hide/show');
assert.deepEqual(errors,[]);assert.deepEqual(http,[]);report.pageErrors=errors;report.httpRequests=http;report.result='PASS';fs.writeFileSync('assets/verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
